import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import React from 'react';
import StyledComponentsRegistry from '~/lib/AntdREgistry';
import { NavGlobal } from '~/components/nav/NavGlobal';
import clsx from 'clsx';
import styles from './layout.module.scss';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko">
      <body className={clsx(inter.className, 'flex', 'flex-row')}>
        <StyledComponentsRegistry>
          <NavGlobal></NavGlobal>
          <div className={clsx('pl-4', styles.layout)}>{children}</div>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
// const Theme = React.createContext({isDarkMode: true})
